DSP Consensus Result Recovery
coti-io/coti-node pull request #45
Opened 2022-10-30 14:43 UTC by dimaru-coti

DCR Resend Solution

2022-11-03 12:18 UTC, dimaru-coti commented on zerospend/src/main/java/io/coti/zerospend/services/NetworkService.java
> +    private String recoveryServerAddress;
move back to initialization service

2022-11-03 12:18 UTC, dimaru-coti commented on zerospend/src/main/java/io/coti/zerospend/services/InitializationService.java
>              }
add back the check for the property and do lookup for node data

2022-11-03 12:18 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeDspVoteService.java
> +    public synchronized void handleDspConsensusResultResend(NodeMessageData nodeMessageData) {
check why synchronized?

2022-11-03 12:18 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeDspVoteService.java
> +                }
else if no DCR found for index break the loop and print error

2022-11-03 12:18 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +            while (!waitingDspConsensusResults.isEmpty()) {
rewrite while loop - return to the previous logic with according implementation

Add synchronization on DCR index

2022-11-03 12:18 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                        long retrievedIndex = candidate.getIndex();
change list to be high and low , add check for not overlapping high and low

2022-11-03 12:18 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeDspVoteService.java
> +    public synchronized void handleDspConsensusResultResend(NodeMessageData nodeMessageData) {
not needed

2022-11-03 12:18 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/data/NodeResendDcrData.java
> +    private Long start;
firstMissedIndex

2022-11-03 12:18 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/data/NodeResendDcrData.java
> +    private Long end;
inRangeLastMissedIndex

2022-11-03 14:47 UTC, gmesika-coti requested changes

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +    private Thread missingIndexesHandler;
Indices

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +    private Thread confirmedDcrTransactionsThread;
dcrMessageHandlerThread

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +    private Thread confirmedTccTransactionsThread;
tccInfoMessageHandlerThread

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +    private void updateConfirmedDcrTransactions() {
updateConfirmedDcrMessages

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +    private void updateConfirmedTccTransactions() {
updateConfirmedTccInfoMessages

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
>              log.info("Please wait to process {} remaining confirmed transaction(s)", remainingConfirmedTransactions.size());
remaining DSP Consensus Results messages

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +            log.info("Please wait to process {} remaining TCC confirmed transaction(s)", remainingConfirmedTransactions.size());
TCC messages

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +            }
if (transactionHelper.isConfirmed(transactionData)) {
                processConfirmedTransaction(transactionData);
            }

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +            if (waitingDspConsensusResults.peek() != null &&
consider moving all to a var

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                while (candidate != null && !waitingDspConsensusResults.isEmpty()) {
count and alert

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                    synchronized (missingIndexesLock) {
take time interval now + Math.random() * 5000) + 3000. if you didnt sleep enough and canidadte is still smaller, complete your sleep

2022-11-03 14:47 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +        return dcrConfirmationQueue.size() + tccConfirmationQueue.size();
split to different queues logs

2022-11-03 14:47 UTC, gmesika-coti commented on zerospend/src/main/java/io/coti/zerospend/services/InitializationService.java
> +                networkService.setRecoveryServer(networkService.getNetworkLastKnownNodeMap().get(new Hash(recoveryServerHash)));
cases: 1. hash not hash. 2. hash not found. 3. check server is in map of network so we wont try to recover from that is not in network

2022-11-06 15:36 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                    candidate.getIndex() == waitingDspConsensusResults.peek().getIndex()) {
add additional check for range if last known index changed

2022-11-06 15:37 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +    private void waitingForIndexResolution(DspConsensusResult candidate) throws InterruptedException {
change to monitor with return boolean value, refactor all the code starting 213

2022-11-06 15:41 UTC, dimaru-coti commented on zerospend/src/main/java/io/coti/zerospend/services/InitializationService.java
> +                log.error("Recovery server node was not updated due to illegal hash string.");
illegal Node hash

2022-11-08 10:02 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                while (candidate != null && !waitingDspConsensusResults.isEmpty()) {
count created, alert will be integrated as part of healthcheck indicator

2022-11-17 09:21 UTC, gmesika-coti requested changes

2022-11-17 09:21 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/ClusterService.java
> +                sourcesStarvationCheckLock.notifyAll();
wait after notify so we will give a chance to copy the data

2022-11-17 09:21 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/TrustChainConfirmationService.java
> +                transactionData -> transactionTrustChainTrustScoreMap.put(transactionData.getHash(), transactionData.getSenderTrustScore()));
plz check if the hasId of the object Double is the same after being copied to the new map as it was in the original object

2022-11-17 09:21 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeNetworkService.java
> +        return new HashMap<>(networkLastKnownNodeMap);
no need to create a new map. maybe just unmodifiable map

2022-11-17 09:21 UTC, gmesika-coti commented on zerospend/src/main/java/io/coti/zerospend/services/SourceStarvationService.java
> +                synchronized (sourcesStarvationCheckLock) {
to remove the global class and use it directly

2022-11-17 09:21 UTC, gmesika-coti commented on zerospend/src/main/java/io/coti/zerospend/services/SourceStarvationService.java
> +                Map<Hash, Double> transactionTrustChainTrustScoreMap = clusterService.getTransactionTrustChainTrustScoreMap();
do the copy and then do notify back

2022-11-30 18:08 UTC, gmesika-coti requested changes

2022-11-30 18:08 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                    sender.send(nodeResendDcrData, networkService.getRecoveryServer().getReceivingFullAddress());
let move the sender code to the service area

2022-11-30 18:08 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                    missingIndexesLock.wait();
lets consider revising this to timewait , check online examples. maybe check waitingDspConsensusResults if empty

2022-11-30 18:08 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                synchronized (missingIndexesLock) {
first do the if in line 201 and if false then do the notifyAll

2022-11-30 18:08 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +        Instant waitingFinalTime = waitingInitialTime.plusMillis(randomWaitingTimeAcrossNodes);
change code by screen shot I sent you

2022-11-30 18:08 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
>              } catch (InterruptedException e) {
all places that do put should also catch Exception e, if it wont be caught the thread will exit and not sure you will be notified

2022-11-30 18:08 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeDspVoteService.java
> +            log.info("Received request for missing dsp consensus results for node: {}", nodeResendDcrData.getHash());
nodehash

2022-11-30 18:08 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeNetworkService.java
> +            if(newSingleNodeData.getReceivingPort() != null) {
what if this is false? put an error

2022-11-30 18:08 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeNetworkService.java
> +                if (currentSingleNodeData != null && currentSingleNodeData.getReceivingPort() != null &&
refactor as disscusssed

2022-11-30 18:08 UTC, gmesika-coti commented on zerospend/src/main/java/io/coti/zerospend/services/SourceStarvationService.java
> +            } catch (InterruptedException e) {
add also in this case exception e

2022-12-01 08:33 UTC, dimaru-coti commented on zerospend/src/main/java/io/coti/zerospend/services/SourceStarvationService.java
> +            } catch (InterruptedException e) {
Added

2022-12-01 09:54 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeNetworkService.java
> +                if (currentSingleNodeData != null && currentSingleNodeData.getReceivingPort() != null &&
done

2022-12-01 09:54 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeNetworkService.java
> +            if(newSingleNodeData.getReceivingPort() != null) {
done

2022-12-01 10:00 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
>              } catch (InterruptedException e) {
Added for all the handler threads

2022-12-01 11:15 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                    missingIndexesLock.wait();
added 1 sec to wait timeout

2022-12-01 11:18 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                synchronized (missingIndexesLock) {
done

2022-12-01 11:19 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +        Instant waitingFinalTime = waitingInitialTime.plusMillis(randomWaitingTimeAcrossNodes);
done

2022-12-01 13:16 UTC, gmesika-coti requested changes

2022-12-01 13:16 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                log.error("Handle Dsp Consensus Result Update got Exception:", e);
please formalize the message

2022-12-01 13:16 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                log.error("Handle Tcc Info Update got Exception:", e);
also

2022-12-01 13:16 UTC, gmesika-coti commented on zerospend/src/main/java/io/coti/zerospend/services/SourceStarvationService.java
> +            } catch (Exception e) {
formalize message

2022-12-01 13:16 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                    sender.send(nodeResendDcrData, networkService.getRecoveryServer().getReceivingFullAddress());
add start and end index and rephrase

2022-12-01 13:16 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                }
add the sleep in the while loop

2022-12-01 13:16 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +    private boolean isRangeValidForResend(DspConsensusResult firstWaitingDcr) throws InterruptedException {
dont return boolean. just void sleep - change name

2022-12-01 13:16 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +        if (isRangeValidForResend(firstWaitingDcr)) {
refactor this sleep to outside method

2022-12-01 13:24 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                log.error("Handle Dsp Consensus Result Update got Exception:", e);
Done

2022-12-01 13:24 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                log.error("Handle Tcc Info Update got Exception:", e);
Done

2022-12-01 13:32 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                }
Added

2022-12-01 13:32 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +        if (isRangeValidForResend(firstWaitingDcr)) {
done

2022-12-01 13:38 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +                    sender.send(nodeResendDcrData, networkService.getRecoveryServer().getReceivingFullAddress());
Done

2022-12-01 13:38 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +    private boolean isRangeValidForResend(DspConsensusResult firstWaitingDcr) throws InterruptedException {
Done

2022-12-01 13:47 UTC, dimaru-coti commented on zerospend/src/main/java/io/coti/zerospend/services/SourceStarvationService.java
> +            } catch (Exception e) {
done

2022-12-01 13:55 UTC, gmesika-coti requested changes

2022-12-01 13:55 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeConfirmationService.java
> +    private static final String EXCEPTION = "Exception: ";
move to string constants

2022-12-12 09:45 UTC, merged