Health indicator
coti-io/coti-node pull request #48
Opened 2022-11-16 11:47 UTC by tomerarm

Health indicators

2022-11-20 10:42 UTC, gmesika-coti requested changes

2022-11-20 10:42 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/controllers/NodeHealthController.java
> +    @GetMapping(path = "/state")
change to /total/state

2022-11-20 10:42 UTC, gmesika-coti commented on nodemanager/src/main/java/io/coti/nodemanager/websocket/WebSocketSender.java
> +        messagingSender.convertAndSend("/topic/healthState/nodes/",
/topic/nodes/health

2022-11-20 10:42 UTC, gmesika-coti commented on nodemanager/src/main/java/io/coti/nodemanager/websocket/WebSocketSender.java
> +        messagingSender.convertAndSend("/topic/healthState/node/" + nodeHash.toString(),
/topic/node/health

2022-11-20 10:42 UTC, gmesika-coti commented on basenode/src/main/resources/application.properties
> +metrics.sample.milisec.interval=6000
remove

2022-11-20 10:42 UTC, gmesika-coti commented on basenode/src/main/resources/application.properties
> +management.endpoint.info.enabled=true
how to limit access to url. maybe just add it to the filter

2022-11-20 10:42 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeDBRecoveryService.java
> +    private BackupInfo lastBackupInfo;
add /getter and remove methods in below below

2022-11-20 10:42 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/http/BaseNodeHealthMetricConstants.java
> +
move to constants dir

2022-11-20 12:19 UTC, tomerarm commented on nodemanager/src/main/java/io/coti/nodemanager/websocket/WebSocketSender.java
> +        messagingSender.convertAndSend("/topic/healthState/node/" + nodeHash.toString(),
Updated

2022-11-20 12:20 UTC, tomerarm commented on nodemanager/src/main/java/io/coti/nodemanager/websocket/WebSocketSender.java
> +        messagingSender.convertAndSend("/topic/healthState/nodes/",
Updated

2022-11-20 12:44 UTC, tomerarm commented on basenode/src/main/resources/application.properties
> +management.endpoint.info.enabled=true
Updated

2022-11-20 12:45 UTC, tomerarm commented on basenode/src/main/java/io/coti/basenode/http/BaseNodeHealthMetricConstants.java
> +
Updated

2023-01-24 11:08 UTC, gmesika-coti commented
no need for this PR. we already refactored code.

2023-01-24 11:08 UTC, closed without merging