dimaru-coti/rejected_transactions_removal
coti-io/coti-node pull request #60
Opened 2023-03-08 12:34 UTC by dimaru-coti

2023-03-08 18:27 UTC, gmesika-coti requested changes

2023-03-08 18:27 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/controllers/BaseNodeAdminController.java
> +    @Operation(summary = "Retrieve List of Rejected Transactions by Admin", operationId = "getRejectedTransactions")
why did you create this method? we have the batch method already

2023-03-08 18:27 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/controllers/BaseNodeAdminController.java
> +            @ApiResponse(responseCode = "200", description = "List of Deleted Rejected Transactions",
description is wrong

2023-03-08 18:27 UTC, gmesika-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeTransactionService.java
> +    @Value("${number.of.days.ttl:30}")
property name not clear . number of days ttl of what? maybe rejected.transaction.ttl ?

2023-03-08 18:27 UTC, gmesika-coti commented on fullnode/src/main/java/io/coti/fullnode/services/TransactionService.java
> +    public ResponseEntity<IResponse> deleteRejectedTransactions(DeleteRejectedTransactionsRequest deleteRejectedTransactionsRequest) {
code should not be duplicated. can move to TransactionHelper

2023-03-08 18:27 UTC, gmesika-coti commented on dspnode/src/main/java/io/coti/dspnode/services/TransactionService.java
> +    public ResponseEntity<IResponse> deleteRejectedTransactions(DeleteRejectedTransactionsRequest deleteRejectedTransactionsRequest) {
code duplicated. can move to TransactionHelper

2023-03-08 18:27 UTC, gmesika-coti commented on dspnode/src/main/java/io/coti/dspnode/services/TransactionService.java
> +                if (rejectedTransaction != null) {
should we do the process if some of the input is wrong?

2023-03-09 08:16 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/controllers/BaseNodeAdminController.java
> +    @Operation(summary = "Retrieve List of Rejected Transactions by Admin", operationId = "getRejectedTransactions")
I have moved it from the DSP node to base as we have discussed that we need it also for Fullnode

2023-03-09 08:17 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/controllers/BaseNodeAdminController.java
> +            @ApiResponse(responseCode = "200", description = "List of Deleted Rejected Transactions",
Why it is not correct?

2023-03-09 08:19 UTC, dimaru-coti commented on fullnode/src/main/java/io/coti/fullnode/services/TransactionService.java
> +    public ResponseEntity<IResponse> deleteRejectedTransactions(DeleteRejectedTransactionsRequest deleteRejectedTransactionsRequest) {
It is not completely same, removeAddressFromRejectedTransactionsMap(rejectedTransaction); is not needed in DSP

2023-03-09 10:17 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/controllers/BaseNodeAdminController.java
> +            @ApiResponse(responseCode = "200", description = "List of Deleted Rejected Transactions",
Successfully deleted rejected transactions

2023-03-09 10:18 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/services/BaseNodeTransactionService.java
> +    @Value("${number.of.days.ttl:30}")
rejected.transactions.days.ttl

2023-03-09 12:14 UTC, dimaru-coti commented on basenode/src/main/java/io/coti/basenode/controllers/BaseNodeAdminController.java
> +            @ApiResponse(responseCode = "200", description = "List of Deleted Rejected Transactions",
Updated

2023-03-09 17:05 UTC, dimaru-coti commented on dspnode/src/main/java/io/coti/dspnode/services/TransactionService.java
> +    public ResponseEntity<IResponse> deleteRejectedTransactions(DeleteRejectedTransactionsRequest deleteRejectedTransactionsRequest) {
moved to BaseNodeTransactionService

2023-03-09 17:05 UTC, dimaru-coti commented on fullnode/src/main/java/io/coti/fullnode/services/TransactionService.java
> +    public ResponseEntity<IResponse> deleteRejectedTransactions(DeleteRejectedTransactionsRequest deleteRejectedTransactionsRequest) {
moved to BaseNodeTransactionService

2023-03-09 17:06 UTC, dimaru-coti commented on dspnode/src/main/java/io/coti/dspnode/services/TransactionService.java
> +                if (rejectedTransaction != null) {
added validation loop with error response on failure

2023-03-11 17:54 UTC, merged